# vim: set ft=toml :


[project]
name = 'antibody-registry'


[tool.pixi.workspace]
channels = ['conda-forge']
platforms = [
  'linux-64',
  'linux-aarch64',
  'osx-arm64',
]

[tool.pixi.dependencies]
python = { version = '>=3.14,<3.15' }

[tool.pixi.pypi-dependencies]
httpx2 = { version = '*', extras = ['http2'] }
lxml = { version = '*' }
orjson = { version = '*' }
pydantic = { version = '*' }
rich = { version = '*' }  # weak dependency of structlog
stamina = { version = '*' }
structlog = { version = '*' }
typer = { version = '*' }

[tool.pixi.environments]
default = { solve-group = 'default' }
lint = { features = ['lint'], solve-group = 'default' }

[tool.pixi.feature.lint.pypi-dependencies]
lxml-stubs = { version = '*' }
mypy = { version = '*' }
ruff = { version = '*' }


[tool.mypy]
allow_redefinition = true
enable_incomplete_feature = [
  'PreciseTupleTypes',
]
install_types = false
native_parser = true
plugins = [
  'pydantic.mypy',
]
python_version = '3.14'
strict = true
warn_unreachable = true


[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true


[tool.ruff]
line-length = 100
target-version = 'py314'

[tool.ruff.format]
preview = true

[tool.ruff.lint]
future-annotations = true
# https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
ignore = [
  'ANN',  # https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
  'C901',  # https://docs.astral.sh/ruff/rules/complex-structure/
  'COM812',  # https://docs.astral.sh/ruff/rules/missing-trailing-comma/
  'COM819',  # https://docs.astral.sh/ruff/rules/prohibited-trailing-comma/
  'CPY',  # https://docs.astral.sh/ruff/rules/#flake8-copyright-cpy
  'D1',  # https://docs.astral.sh/ruff/rules/#pydocstyle-d
  'D300',  # https://docs.astral.sh/ruff/rules/triple-single-quotes/
  'E111',  # https://docs.astral.sh/ruff/rules/indentation-with-invalid-multiple/
  'E114',  # https://docs.astral.sh/ruff/rules/indentation-with-invalid-multiple-comment/
  'E117',  # https://docs.astral.sh/ruff/rules/over-indented/
  'ERA',  # https://docs.astral.sh/ruff/rules/#eradicate-era
  'FIX002',  # https://docs.astral.sh/ruff/rules/line-contains-todo/
  'ISC001',  # https://docs.astral.sh/ruff/rules/single-line-implicit-string-concatenation/
  'PLR0912',  # https://docs.astral.sh/ruff/rules/too-many-branches/
  'PLR0913',  # https://docs.astral.sh/ruff/rules/too-many-arguments/
  'PLR0915',  # https://docs.astral.sh/ruff/rules/too-many-statements/
  'Q000',  # https://docs.astral.sh/ruff/rules/bad-quotes-inline-string/
  'Q001',  # https://docs.astral.sh/ruff/rules/bad-quotes-multiline-string/
  'Q002',  # https://docs.astral.sh/ruff/rules/bad-quotes-docstring/
  'Q003',  # https://docs.astral.sh/ruff/rules/avoidable-escaped-quote/
  'Q004',  # https://docs.astral.sh/ruff/rules/unnecessary-escaped-quote/
  'S603',  # https://docs.astral.sh/ruff/rules/subprocess-without-shell-equals-true/
  'S606',  # https://docs.astral.sh/ruff/rules/start-process-with-no-shell/
  'S607',  # https://docs.astral.sh/ruff/rules/start-process-with-partial-path/
  'T201',  # https://docs.astral.sh/ruff/rules/print/
  'TD002',  # https://docs.astral.sh/ruff/rules/missing-todo-author/
  'TD003',  # https://docs.astral.sh/ruff/rules/missing-todo-link/
  'W191',  # https://docs.astral.sh/ruff/rules/tab-indentation/
]
select = ['ALL']

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = []
known-local-folder = [
  'logging_config',
  'pydantic_base_model',
  'secret',
]
known-third-party = [
  'httpx2',
  'lxml',
  'orjson',
  'pydantic',
  'stamina',
  'structlog',
  'typer',
]

[tool.ruff.lint.pydocstyle]
convention = 'pep257'
